backend:
  name: git-gateway
  repo: notcooley/notcooley.github.io
  branch: main
  identity_url: https://lovely-blancmange-41b7b2.netlify.app/.netlify/identity
  gateway_url: https://lovely-blancmange-41b7b2.netlify.app/.netlify/git/github

media_folder: /images
public_folder: /images

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
